=== Swarima/htmlandxml/XMLxsdproject/bin/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zensar.com/Movies" xmlns:zen="http://www.zensar.com/Movies" elementFormDefault="qualified">
	<element name="movies">
		<complexType>
			<sequence>
			<element name="movie" maxOccurs="unbounded">
			<complexType>
			<sequence>
				<element name="code">
					<simpleType>
						<restriction base="int">
							<totalDigits value="4"></totalDigits>
							<minInclusive value="5001"></minInclusive>
							<maxInclusive value="6000"></maxInclusive>
						</restriction>
					</simpleType>
				</element>
				<element name="title" type="string"></element>
				<element name="release-date" type="date" minOccurs="0"></element>
				<element name="theater-name">
				<simpleType>
						<restriction base="string">
						<minLength value="4"></minLength>
						<maxLength value="20"></maxLength>
				</restriction>
				</simpleType>
				</element>
			 </sequence>
		</complexType>
	</element>
	</sequence>
		</complexType>
	</element>
</schema>

=== Swarima/htmlandxml/XMLxsdproject/bin/moviedetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<zen:movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:zen="http://www.zensar.com/Movies" xsi:schemaLocation="http://www.zensar.com/Movies movies.xsd ">
  <zen:movie>
    <zen:code>5231</zen:code>
    <zen:title>aao dekhe</zen:title>
        <zen:release-date>2019-08-15</zen:release-date>
    	 <zen:theater-name>inox</zen:theater-name>
   </zen:movie>
   
    <zen:movie>
    <zen:code>5009</zen:code>
    <zen:title>vghikjk</zen:title>
        <zen:release-date>2000-01-15</zen:release-date>
    	 <zen:theater-name>inox</zen:theater-name>
    
  </zen:movie>
</zen:movies>
